FileExistsError: [Errno 17] File exists: 'm5out'

At:
  /usr/lib64/python3.9/os.py(230): makedirs
  src/python/m5/main.py(417): main

 Performance counter stats for '/home/mcallisl/gem5/build/ALL/gem5.opt /home/mcallisl/perf_automation/gem5_config.py --isa X86 --cpu O3 --mem 2GiB --cache 32KiB:256KiB --cores 4 --workload blackscholes':

        48,517,637      CPU_CLK_UNHALTED.REF_XCLK        #     24.9 %  tma_frontend_bound     
                                                  #      9.9 %  tma_bad_speculation    
                                                  #     30.5 %  tma_retiring           
                                                  #     34.7 %  tma_backend_bound        (49.73%)
        42,926,512      IDQ.MS_UOPS                                                             (49.95%)
     1,439,907,296      IDQ_UOPS_NOT_DELIVERED.CORE                                             (50.15%)
        57,835,893      INT_MISC.RECOVERY_CYCLES_ANY                                            (50.31%)
        48,384,072      CPU_CLK_UNHALTED.ONE_THREAD_ACTIVE                                        (50.27%)
     1,449,872,766      CPU_CLK_UNHALTED.THREAD                                                 (50.05%)
     1,768,628,901      UOPS_RETIRED.RETIRE_SLOTS                                               (49.85%)
     2,224,390,339      UOPS_ISSUED.ANY                                                         (49.69%)

       0.491620466 seconds time elapsed

       0.444404000 seconds user
       0.041430000 seconds sys


